'\" t
.\"     Title: example
.\"    Author: Doc Writer
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2024-08-01
.\"    Manual: bin manual
.\"    Source: bin 0.1.0
.\"  Language: English
.\"
.TH "EXAMPLE" "1" "2024-08-01" "bin 0.1.0" "bin manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
example \- a binary that do stuff
.SH "SYNOPSIS"
.sp
\fBexample\fP [\fIOPTION\fP]... \fIFILE\fP...
.SH "DESCRIPTION"
.sp
\fIZen\fP in the \fBart\fP of writing \f(CRplain text\fP with \c
.URL "https://asciidoc.org" "AsciiDoc" "."
.SS "Settings"
.sp
\fB\-B, \-\-base\-dir\fP=\fIDIR\fP
.RS 4
Something goes here, like a very long text, perhaps.
Then something else goes here.
Yet something else entirely.
.RE
.SS "More settings"
.sp
Use \c
.URL "https://asciidoctor.org" "AsciiDoctor" ""
for the best AsciiDoc experience.[1] Then [twitter] about it!
.SH "SAMPLE SECTION"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
item 1
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
item 2
.RE
.sp
.if n .RS 4
.nf
.fam C
puts "Hello, World!"
.fam
.fi
.if n .RE
.SH "NOTES"
.IP [1]
Not to mention the best looking output!
.SH "AUTHOR"
.sp
Doc Writer